/* contingency C API — auto-generated by cbindgen. Do not edit. */

#ifndef CONTINGENCY_H
#define CONTINGENCY_H

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Floating-point tolerance used uniformly across all monotonic-time
 * and event-time equality checks. Mirrors `TIME_TOL` in
 * `contingency-py`. A Rust port that uses a different tolerance will
 * diverge from the Python implementation on boundary-equal
 * conformance fixtures.
 */
#define TIME_TOL 1e-9

/**
 * Opaque handle to an armable interval schedule (FI / VI / RI).
 *
 * Only used as an intermediary for constructing limited-hold
 * compounds; do not step or reset directly. Consumed by
 * [`opk_limited_hold_fi`], [`opk_limited_hold_vi`],
 * [`opk_limited_hold_ri`] (which take ownership).
 */
typedef struct OpkArmableSchedule OpkArmableSchedule;

/**
 * Opaque handle to a heap-allocated schedule.
 *
 * Construct with any `opk_*` schedule constructor, step with
 * [`opk_schedule_step`], and release with [`opk_schedule_free`].
 */
typedef struct OpkSchedule OpkSchedule;

/**
 * Plain-old-data mirror of [`crate::Outcome`] for C consumers.
 *
 * Only the `reinforced` flag is meaningful when no reinforcer was
 * delivered; the remaining fields are zero-initialised in that case.
 * `reinforcer_label`, when non-NULL, is borrowed from the schedule
 * handle and remains valid until the next [`opk_schedule_step`] call
 * on that handle or until the handle is freed.
 */
typedef struct {
  /**
   * Whether the step produced a reinforcement delivery.
   */
  bool reinforced;
  /**
   * Delivery time. Valid only when `reinforced` is `true`.
   */
  double reinforcer_time;
  /**
   * Delivery magnitude. Valid only when `reinforced` is `true`.
   */
  double reinforcer_magnitude;
  /**
   * NUL-terminated reinforcer label. NULL when `reinforced` is
   * `false`. Otherwise valid until the next `opk_schedule_step` call
   * on the same schedule handle. Caller must NOT free.
   */
  const char *reinforcer_label;
} OpkOutcome;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return a pointer to the last error message for this thread, or NULL
 * if no error has been recorded. The returned pointer is valid until
 * the next FFI call that sets an error on this thread and must not be
 * freed by the caller.
 */
const char *opk_last_error_message(void);

/**
 * Clear the thread-local error channel.
 */
void opk_clear_last_error(void);

/**
 * Release a schedule handle. Safe to call with NULL.
 *
 * # Safety
 *
 * `handle` must be either NULL or a pointer previously returned by an
 * `opk_*` schedule constructor and not yet freed.
 */
void opk_schedule_free(OpkSchedule *handle);

/**
 * Release an armable schedule handle. Safe to call with NULL.
 *
 * # Safety
 *
 * `handle` must be either NULL or a pointer previously returned by an
 * `opk_armable_*` constructor and not yet freed or consumed by a
 * limited-hold constructor.
 */
void opk_armable_schedule_free(OpkArmableSchedule *handle);

/**
 * Step a schedule. Returns `0` on success, non-zero on error.
 *
 * * `now` — monotonic clock time. Must be `>=` the previous step's
 *   `now` within [`crate::TIME_TOL`].
 * * `has_event` — when `true`, a response event is supplied with
 *   `event_time` and `event_operandum`. `event_operandum` must be a
 *   valid NUL-terminated UTF-8 string for the duration of this call.
 *   When `has_event` is `false`, `event_time` and `event_operandum`
 *   are ignored.
 * * `out` — receives the outcome; must point to a writable
 *   [`OpkOutcome`]. `reinforcer_label` in the written outcome borrows
 *   memory from the schedule handle and remains valid until the next
 *   step call on this handle.
 *
 * On error, `*out` is set to an empty (non-reinforced) outcome.
 * Retrieve the error message via [`opk_last_error_message`].
 *
 * # Safety
 *
 * * `handle` must be a non-null pointer returned by an `opk_*`
 *   constructor and not yet freed.
 * * `out` must be a non-null, suitably-aligned pointer to a writable
 *   [`OpkOutcome`].
 * * When `has_event` is `true`, `event_operandum` must be a valid
 *   NUL-terminated UTF-8 string valid for the duration of the call.
 */
int opk_schedule_step(OpkSchedule *handle,
                      double now,
                      bool has_event,
                      double event_time,
                      const char *event_operandum,
                      OpkOutcome *out);

/**
 * Reset a schedule to its post-construction state.
 *
 * # Safety
 *
 * `handle` must be a non-null pointer returned by an `opk_*`
 * constructor and not yet freed.
 */
int opk_schedule_reset(OpkSchedule *handle);

/**
 * Fixed-Ratio schedule with requirement `n`.
 * Returns NULL on failure; retrieve the error via
 * [`opk_last_error_message`].
 */
OpkSchedule *opk_fr(uint64_t n);

/**
 * Continuous Reinforcement (FR 1).
 */
OpkSchedule *opk_crf(void);

/**
 * Variable-Ratio schedule (Fleshler-Hoffman progression).
 *
 * * `mean` — mean ratio requirement.
 * * `n_intervals` — number of values in the pre-generated sequence.
 * * `has_seed` — when `true`, use `seed`; when `false`, sample a
 *   non-deterministic seed.
 */
OpkSchedule *opk_vr(double mean, uintptr_t n_intervals, bool has_seed, uint64_t seed);

/**
 * Random-Ratio schedule (Bernoulli per response).
 */
OpkSchedule *opk_rr(double probability, bool has_seed, uint64_t seed);

/**
 * Fixed-Interval schedule with `interval` time units.
 */
OpkSchedule *opk_fi(double interval);

/**
 * Variable-Interval schedule (Fleshler-Hoffman progression).
 */
OpkSchedule *opk_vi(double mean_interval, uintptr_t n_intervals, bool has_seed, uint64_t seed);

/**
 * Random-Interval schedule (exponential).
 */
OpkSchedule *opk_ri(double mean_interval, bool has_seed, uint64_t seed);

/**
 * FI armable-schedule handle (only for use with `opk_limited_hold_fi`).
 */
OpkArmableSchedule *opk_armable_fi(double interval);

/**
 * VI armable-schedule handle.
 */
OpkArmableSchedule *opk_armable_vi(double mean_interval,
                                   uintptr_t n_intervals,
                                   bool has_seed,
                                   uint64_t seed);

/**
 * RI armable-schedule handle.
 */
OpkArmableSchedule *opk_armable_ri(double mean_interval, bool has_seed, uint64_t seed);

/**
 * Wrap an FI schedule with a limited-hold window. Takes ownership of
 * `inner`; on success the inner handle must NOT be freed separately.
 * On failure, `inner` is freed by this function.
 *
 * # Safety
 *
 * `inner` must be a valid pointer previously returned by
 * [`opk_armable_fi`] and not yet freed or consumed.
 */
OpkSchedule *opk_limited_hold_fi(OpkArmableSchedule *inner, double hold);

/**
 * Wrap a VI schedule with a limited-hold window.
 *
 * # Safety
 *
 * `inner` must be a valid pointer previously returned by
 * [`opk_armable_vi`] and not yet freed or consumed.
 */
OpkSchedule *opk_limited_hold_vi(OpkArmableSchedule *inner, double hold);

/**
 * Wrap an RI schedule with a limited-hold window.
 *
 * # Safety
 *
 * `inner` must be a valid pointer previously returned by
 * [`opk_armable_ri`] and not yet freed or consumed.
 */
OpkSchedule *opk_limited_hold_ri(OpkArmableSchedule *inner, double hold);

/**
 * Fixed-Time schedule (non-contingent).
 */
OpkSchedule *opk_ft(double interval);

/**
 * Variable-Time schedule (Fleshler-Hoffman).
 */
OpkSchedule *opk_vt(double mean_interval, uintptr_t n_intervals, bool has_seed, uint64_t seed);

/**
 * Random-Time schedule (exponential).
 */
OpkSchedule *opk_rt(double mean_interval, bool has_seed, uint64_t seed);

/**
 * Extinction schedule (never reinforces).
 */
OpkSchedule *opk_ext(void);

/**
 * Differential Reinforcement of Other behaviour — resetting timer.
 */
OpkSchedule *opk_dro_resetting(double interval);

/**
 * Differential Reinforcement of Other behaviour — momentary (whole-interval).
 */
OpkSchedule *opk_dro_momentary(double interval);

/**
 * Differential Reinforcement of Low rates.
 */
OpkSchedule *opk_drl(double interval);

/**
 * Differential Reinforcement of High rates.
 */
OpkSchedule *opk_drh(uint32_t response_count, double time_window);

/**
 * Progressive-Ratio schedule with arithmetic step.
 */
OpkSchedule *opk_pr_arithmetic(uint32_t start, uint32_t step);

/**
 * Progressive-Ratio schedule with geometric step.
 */
OpkSchedule *opk_pr_geometric(uint32_t start, double ratio);

/**
 * Progressive-Ratio schedule using the Richardson-Roberts (1996) series.
 */
OpkSchedule *opk_pr_richardson_roberts(void);

/**
 * Construct Alternative(first, second). Takes ownership of both
 * handles — caller MUST NOT free them separately. Handles remain
 * valid for the lifetime of the returned Alternative handle;
 * `opk_schedule_free` on the returned handle drops all nested
 * schedules.
 *
 * Returns NULL and sets the thread-local error when either handle is
 * NULL. In the NULL case any non-NULL handle passed in is freed
 * eagerly so the caller never double-frees.
 *
 * # Safety
 *
 * `first` and `second` must be valid handles previously created by an
 * `opk_*` constructor. After this call they must NOT be used again.
 */
OpkSchedule *opk_alternative(OpkSchedule *first, OpkSchedule *second);

/**
 * Multiple compound schedule. Takes ownership of every component.
 *
 * * `components` — array of `len` schedule handles.
 * * `stimuli` — optional array of `len` NUL-terminated UTF-8 stimulus
 *   labels. Pass NULL to skip.
 *
 * On failure, all component handles are freed; the returned pointer
 * is NULL.
 *
 * # Safety
 *
 * * `components` must point to `len` valid schedule handles.
 * * When `stimuli` is non-NULL, it must point to `len` valid
 *   NUL-terminated UTF-8 strings.
 */
OpkSchedule *opk_multiple(OpkSchedule *const *components,
                          uintptr_t len,
                          const char *const *stimuli);

/**
 * Chained compound schedule. Takes ownership of every component.
 *
 * # Safety
 *
 * Same contract as [`opk_multiple`].
 */
OpkSchedule *opk_chained(OpkSchedule *const *components, uintptr_t len, const char *const *stimuli);

/**
 * Tandem compound schedule. Takes ownership of every component.
 *
 * # Safety
 *
 * `components` must point to `len` valid schedule handles.
 */
OpkSchedule *opk_tandem(OpkSchedule *const *components, uintptr_t len);

/**
 * Concurrent compound schedule keyed by operandum name. Takes ownership
 * of every component.
 *
 * * `operanda` — array of `len` NUL-terminated UTF-8 operandum keys.
 *   Duplicates are rejected.
 * * `components` — array of `len` schedule handles, paired 1:1 with
 *   `operanda`.
 * * `cod` — changeover delay.
 * * `cor` — changeover ratio.
 *
 * On failure, every component handle is freed.
 *
 * # Safety
 *
 * * `operanda` must point to `len` valid NUL-terminated UTF-8 strings.
 * * `components` must point to `len` valid schedule handles.
 */
OpkSchedule *opk_concurrent(const char *const *operanda,
                            OpkSchedule *const *components,
                            uintptr_t len,
                            double cod,
                            uint32_t cor);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CONTINGENCY_H */
